# =====================================================================
# ne_country_names.R
#
# Mapping from the HIV dataset's country names to the names used by
# rnaturalearth, e.g.
#   "Congo (the Democratic Republic of the)" -> "Dem. Rep. Congo"
#
# Source this from any script that joins our data to map polygons:
#   source("ne_country_names.R")
#
# Provides: country_name_corrections, ne_name()
# =====================================================================


# Packages are loaded by 00_libraries.R (see run_all.R).
country_name_corrections <- c(
  #latin america and caribbean   
  "Anguilla" = "Anguilla",
  "Antigua & Barbuda" = "Antigua and Barb.",
  "Aruba" = "Aruba",
  "Bahamas" = "Bahamas",
  "Barbados" = "Barbados",
  "British Virgin Islands" = "British Virgin Is.",
  "Cayman Islands" = "Cayman Is.",
  "Cuba" = "Cuba",
  "Dominica" = "Dominica",
  "Dominican Republic (the)" = "Dominican Rep.",
  "Grenada" = "Grenada",
  "Guadeloupe" = "Guadeloupe",
  "Haiti" = "Haiti",
  "Jamaica" = "Jamaica",
  "Martinique" = "Martinique",
  "Montserrat" = "Montserrat",
  "Puerto Rico" = "Puerto Rico",
  "St. Kitts & Nevis" = "St. Kitts and Nevis",
  "St. Lucia" = "Saint Lucia",
  "St. Vincent & Grenadines" = "St. Vin. and Gren.",
  "Trinidad and Tobago" = "Trinidad and Tobago",
  "Turks & Caicos Islands" = "Turks and Caicos Is.",
  "U.S. Virgin Islands" = "U.S. Virgin Is.",
  "Belize" = "Belize",
  "Costa Rica" = "Costa Rica",
  "El Salvador" = "El Salvador",
  "Guatemala" = "Guatemala",
  "Honduras" = "Honduras",
  "Mexico" = "Mexico",
  "Nicaragua" = "Nicaragua",
  "Panama" = "Panama",
  "Argentina" = "Argentina",
  "Bolivia (Plurinational State of)" = "Bolivia",
  "Brazil" = "Brazil",
  "Chile" = "Chile",
  "Colombia" = "Colombia",
  "Ecuador" = "Ecuador",
  "Falkland Islands" = "Falkland Is.",
  "French Guiana" = "French Guiana",
  "Guyana" = "Guyana",
  "Paraguay" = "Paraguay",
  "Peru" = "Peru",
  "Suriname" = "Suriname",
  "Uruguay" = "Uruguay",
  "Venezuela (Bolivarian Republic of)" = "Venezuela",
  "Sint Maarten" = "Sint Maarten",
  "Curaçao" = "Curaçao",
  
  #Africa
  "Burundi" = "Burundi",
  "Comoros" = "Comoros",
  "Djibouti" = "Djibouti",
  "Eritrea" = "Eritrea",
  "Ethiopia" = "Ethiopia",
  "Kenya" = "Kenya",
  "Madagascar" = "Madagascar",
  "Malawi" = "Malawi",
  "Mauritius" = "Mauritius",
  "Mayotte" = "Mayotte",
  "Mozambique" = "Mozambique",
  "Réunion" = "Réunion",
  "Rwanda" = "Rwanda",
  "Seychelles" = "Seychelles",
  "Somalia" = "Somalia",
  "Uganda" = "Uganda",
  "Tanzania, the United Republic of" = "Tanzania",
  "Zambia" = "Zambia",
  "Zimbabwe" = "Zimbabwe",
  "Angola" = "Angola",
  "Cameroon" = "Cameroon",
  "Central African Republic (the)" = "Central African Rep.",
  "Chad" = "Chad",
  "Congo (the)" = "Congo",
  "Congo (the Democratic Republic of the)" = "Dem. Rep. Congo",
  "Equatorial Guinea" = "Eq. Guinea",
  "Gabon" = "Gabon",
  "São Tomé & Príncipe" = "São Tomé and Principe",
  "Algeria" = "Algeria",
  "Egypt" = "Egypt",
  "Libya" = "Libya",
  "Morocco" = "Morocco",
  "Sudan (the)" = "Sudan",
  "Tunisia" = "Tunisia",
  "Western Sahara" = "W. Sahara",
  "Botswana" = "Botswana",
  "Eswatini" = "eSwatini",
  "Lesotho" = "Lesotho",
  "Namibia" = "Namibia",
  "South Africa" = "South Africa",
  "Benin" = "Benin",
  "Burkina Faso" = "Burkina Faso",
  "Cabo Verde" = "Cabo Verde",
  "Côte d'Ivoire" = "Côte d'Ivoire",
  "Gambia (the)" = "Gambia",
  "Ghana" = "Ghana",
  "Guinea" = "Guinea",
  "Guinea-Bissau" = "Guinea-Bissau",
  "Liberia" = "Liberia",
  "Mali" = "Mali",
  "Mauritania" = "Mauritania",
  "Niger (the)" = "Niger",
  "Nigeria" = "Nigeria",
  "St. Helena" = "Saint Helena",
  "Senegal" = "Senegal",
  "Sierra Leone" = "Sierra Leone",
  "Togo" = "Togo",
  "South Sudan" = "S. Sudan",
  "Seychelles" = "Seychelles",
  
  #Europe
  "Uzbekistan" = "Uzbekistan",
  "Kyrgyzstan" = "Kyrgyzstan",
  "Tajikistan" = "Tajikistan",
  "Turkmenistan" = "Turkmenistan",
  "Kazakhstan" = "Kazakhstan",
  "Belarus" = "Belarus",
  "Bulgaria" = "Bulgaria",
  "Czechia" = "Czechia",
  "Hungary" = "Hungary",
  "Poland" = "Poland",
  "Moldova (the Republic of)" = "Moldova",
  "Romania" = "Romania",
  "Russian Federation (the)" = "Russia",
  "Slovakia" = "Slovakia",
  "Ukraine" = "Ukraine",
  "Denmark" = "Denmark",
  "Estonia" = "Estonia",
  "Faroe Islands" = "Faeroe Is.",
  "France" = "France",
  "Finland" = "Finland",
  "Iceland" = "Iceland",
  "Ireland" = "Ireland",
  "Isle of Man" = "Isle of Man",
  "Latvia" = "Latvia",
  "Lithuania" = "Lithuania",
  "Norway" = "Norway",
  "Sweden" = "Sweden",
  "United Kingdom of Great Britain and Northern Ireland (the)" = "United Kingdom",
  "Albania" = "Albania",
  "Andorra" = "Andorra",
  "Bosnia and Herzegovina" = "Bosnia and Herz.",
  "Croatia" = "Croatia",
  "Gibraltar" = "Gibraltar",
  "Greece" = "Greece",
  "Italy" = "Italy",
  "Malta" = "Malta",
  "North Macedonia" = "North Macedonia",
  "Portugal" = "Portugal",
  "San Marino" = "San Marino",
  "Serbia & Montenegro" = "Serbia",
  "Slovenia" = "Slovenia",
  "Spain" = "Spain",
  "Austria" = "Austria",
  "Belgium" = "Belgium",
  "France" = "France",
  "Liechtenstein" = "Liechtenstein",
  "Luxembourg" = "Luxembourg",
  "Monaco" = "Monaco",
  "Netherlands (the)" = "Netherlands",
  "Switzerland" = "Switzerland",
  "Montenegro" = "Montenegro",
  "Vatican" = "Vatican",
  "Jersey" = "Jersey",
  "Guernsey" = "Guernsey",
  "Åland" = "Åland",
  
  #Asia Oceania
  "China" = "China",
  "Hong Kong" = "Hong Kong",
  "Macao SAR" = "Macao",
  "North Korea" = "North Korea",
  "Japan" = "Japan",
  "Mongolia" = "Mongolia",
  "Korea (the Republic of)" = "South Korea",
  "Brunei" = "Brunei",
  "Cambodia" = "Cambodia",
  "Indonesia" = "Indonesia",
  "Lao People's Democratic Republic (the)" = "Laos",
  "Malaysia" = "Malaysia",
  "Myanmar" = "Myanmar",
  "Philippines (the)" = "Philippines",
  "Singapore" = "Singapore",
  "Thailand" = "Thailand",
  "Timor-Leste" = "Timor-Leste",
  "Viet Nam" = "Vietnam",
  "Afghanistan" = "Afghanistan",
  "Bangladesh" = "Bangladesh",
  "Bhutan" = "Bhutan",
  "India" = "India",
  "Iran (Islamic Republic of)" = "Iran",
  "Maldives" = "Maldives",
  "Nepal" = "Nepal",
  "Pakistan" = "Pakistan",
  "Sri Lanka" = "Sri Lanka",
  "Armenia" = "Armenia",
  "Azerbaijan" = "Azerbaijan",
  "Bahrain" = "Bahrain",
  "Cyprus" = "Cyprus",
  "Georgia" = "Georgia",
  "Iraq" = "Iraq",
  "Israel" = "Israel",
  "Jordan" = "Jordan",
  "Kuwait" = "Kuwait",
  "Lebanon" = "Lebanon",
  "Oman" = "Oman",
  "Qatar" = "Qatar",
  "Saudi Arabia" = "Saudi Arabia",
  "Palestine" = "Palestine",
  "Syria" = "Syria",
  "Turkey" = "Turkey",
  "United Arab Emirates" = "United Arab Emirates",
  "Yemen" = "Yemen",
  "Australia" = "Australia",
  "New Zealand" = "New Zealand",
  "Fiji" = "Fiji",
  "New Caledonia" = "New Caledonia",
  "Papua New Guinea" = "Papua New Guinea",
  "Solomon Islands" = "Solomon Is.",
  "Vanuatu" = "Vanuatu",
  "Guam" = "Guam",
  "Kiribati" = "Kiribati",
  "Marshall Islands" = "Marshall Is.",
  "FS Micronesia" = "Micronesia",
  "Nauru" = "Nauru",
  "Northern Mariana Islands" = "N. Mariana Is.",
  "Palau" = "Palau",
  "American Samoa" = "American Samoa",
  "Cook Islands" = "Cook Is.",
  "French Polynesia" = "Fr. Polynesia",
  "Niue" = "Niue",
  "Samoa" = "Samoa",
  "Tokelau" = "Tokelau",
  "Tonga" = "Tonga",
  "Tuvalu" = "Tuvalu",
  "Wallis & Futuna" = "Wallis and Futuna Is.",
  
  #North America
  
  "United States of America (the)"= "United States of America"
)

# Apply the mapping, leaving unmatched names unchanged
ne_name <- function(x) {
  ifelse(x %in% names(country_name_corrections),
         unname(country_name_corrections[x]), x)
}
